# permissions for end users to view memcachedhas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: memcachedha-viewer-role
rules:
- apiGroups:
  - cache.naches.cn
  resources:
  - memcachedhas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.naches.cn
  resources:
  - memcachedhas/status
  verbs:
  - get
