# permissions for end users to edit memcachedhas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: memcachedha-editor-role
rules:
- apiGroups:
  - cache.naches.cn
  resources:
  - memcachedhas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.naches.cn
  resources:
  - memcachedhas/status
  verbs:
  - get
